### PR TITLE
Do not show Output on LSP completion error

### PR DESCRIPTION
**Pull request by iacore**
Stop VSCode from showing Output channel on error.

### CODE REVIEW

**Comment by bung87** [comment]
if it's an error why not show it out?

**Comment by iacore** [comment]
When editing, malformed AST will create error and show Output tab. This is annoying, since I need to jump back to Terminal tab every time I edit.

For example, try to edit the code `proc foo: int = 42` and put cursor like `pro|c`, then press some spaces.

An alternative is to patch nimlsp to behave, but I'm not good at that.

**Comment by bung87** [comment]
thanks for explain , I think it should be resolve in nimlsp or identify this kind of error on client side

**Comment by iacore** [comment]
Sometimes nimlsp will not return result or error for a request.

There is some code in vscode-lsp-client that raise the error.

**Comment by bung87** [comment]
yeah that's annoying, it should silently log out , I ll merge this

**Pull request merged**
